name: Evercode checks

on:
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn

      - name: Evercode checks
        uses: 'devpass-tech/gitaction-testfile@v1'
        with:
          repo_name: ${{ github.repository }}
          branch_name: ${{ github.head_ref }}
